### ISSUE TITLE
Comentario/documentación sobre pipe→leftcmd,rightcmd

### ISSUE THREAD

**Issue by dato** [fisop/labs#2]
En clase de consultas me llamaron la atención sobre este comentario en _types.h_:

https://github.com/fisop/labs/blob/70bc148b97cb17ac44c91f05fc6dfde70a3dd693/shell/types.h#L55-L59

Lo que, en particular, encontraron confuso es la frase “it means that they can be either an EXEC or a REDIR command”, pues  —tomado prescriptivamente— está en contradicción directa con nuestra propuesta de implementación recursiva.

**Comment by PatricioIribarneCatella** [comment]
Correcto. Resulto en PR: https://github.com/fisop/labs/pull/6
