### ISSUE TITLE
Añadir la opción -nostdinc en la compilación de kern0

### ISSUE THREAD

**Issue by dato** [fisop/labs#5]
Vi un kern0 que hacía `#include <stdio.h>` aunque no lo usase; pero eso
no debería compilar.

También se podría añadir `-ffreestanding` (o `-fno-hosted`, es lo mismo),
para ser enteramente correctos, y de paso explicar lo que hace.

**Comment by PatricioIribarneCatella** [comment]
Correcto. Se resuelve en el PR: #7
